### PR TITLE
Add English labels

### PR DESCRIPTION
**Pull request by acka47**
As discussed in yesterday's OERSI meeting (see [to dos](https://pad.gwdg.de/wMwBTWpNSjOBWKOPfNdErw?view#To-Dos-2172020)).

### CODE REVIEW

**Comment by axel-klinger** [comment]
Hi, thanks for this first version. Just some things, that I would suggest to fix:
- use capital letters also for English terms, because the labels act like headers, see also https://oasis.geneseo.edu/basic_search.php?search_query=math
- use Audio instead of Tonaufnahme - sounds more modern
- use Kurs instead of Lernkurs - it is clear enough in the context of education
- maybe Bild instead of Abbildung?
- use Präsentation instead of Präsentationsfolien - nobody should use classic "Folien" in the future
- use Text instead of Textdokument - we also do not talk about Audiodokument or Videodokument

Additional material suggestion:
- Lektion (de, s.a. Kapitel), lesson (en, s.a. chapter): component of a course, consist of one or more elements of (audio|video|text|exercise|...) - should be some kind of a didactic unit

**Comment by acka47** [comment]
Thanks @axel-klinger for these good suggestions for improvement. Re. captial letters, I followed the example of LRMI vocabs but I am fine with changing it and added a corresponding commit in which I also changed "educational game" to "Game" and "presentation slides" to "presentation".

Re. updating German labels: I support all those proposals but don't want to just implement them without at least consulting @mic-men: Are those changes ok for you too, Michael? If yes, I suggest to proceed as follows: Merge this PR, then open another one with the German label changes and notify on the OER-Metadatengruppe list about the pending changes. If nobody objects, we can merge it. (This would also be a test for implementing bigger changes like @axel-klinger's proposal for adding some more types.)

**Comment by acka47** [comment]
BTW, the `addEnglishLabels` branch can also be viewed on SkoHub, see https://skohub.io/dini-ag-kim/hcrt/heads/addEnglishLabels/w3id.org/kim/hcrt/scheme.html. However, as we do not support internationalization in the HTML representation yet (see https://github.com/hbz/skohub-vocabs/issues/79), this does not differ much from the main version and thus in this case is not suited for review purposes.

**Comment by mic-men** [comment]
I agree with the proposals by @axel-klinger for changing German labels - only for "Bild" instead of "Abbildung" I don't see the point but it's not really important to me.
For additional materials let's postpone that a bit. I think it needs more discussion.

**Pull request merged**
